# Generated by Django 5.1.5 on 2025-05-01 22:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="listing",
            name="villain",
        ),
        migrations.AddField(
            model_name="listing",
            name="short_name",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="listing",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="listing",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
