# Generated by Django 5.1.5 on 2025-05-02 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0002_remove_listing_villain_listing_short_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="short_name",
            field=models.CharField(default="", max_length=200),
        ),
    ]
