# Generated by Django 5.1.5 on 2025-05-14 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0003_alter_listing_short_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="pictures_lg",
            field=models.FilePathField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="listing",
            name="pictures_sm",
            field=models.FilePathField(blank=True, null=True),
        ),
    ]
