# Generated by Django 5.1.5 on 2025-05-14 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0005_alter_listing_pictures_lg_alter_listing_pictures_sm"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="pictures_lg",
            field=models.FilePathField(
                default="static/img/listings/temp_photos", match="*.jpg", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="pictures_sm",
            field=models.FilePathField(
                default="static/img/listings/temp_photos", match="*.jpg", max_length=200
            ),
        ),
    ]
