# Generated by Django 5.1.5 on 2025-05-14 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0007_alter_listing_pictures_lg_alter_listing_pictures_sm"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="pictures_lg",
            field=models.FilePathField(
                default="static/img/listings/temp_photos",
                match=".*\\.(jpg|png)$",
                max_length=200,
                path="static/img/listings/temp_photos",
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="pictures_sm",
            field=models.FilePathField(
                default="static/img/listings/temp_photos",
                match=".*\\.(jpg|png)$",
                max_length=200,
                path="static/img/listings/temp_photos",
            ),
        ),
    ]
