# Generated by Django 5.1.5 on 2025-05-15 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0008_alter_listing_pictures_lg_alter_listing_pictures_sm"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="listing",
            name="pictures_lg",
        ),
        migrations.RemoveField(
            model_name="listing",
            name="pictures_sm",
        ),
        migrations.CreateModel(
            name="ListingImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_lg", models.ImageField(upload_to="listing_images")),
                ("image_sm", models.ImageField(upload_to="listing_images")),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="listings.listing",
                    ),
                ),
            ],
        ),
    ]
