# Generated by Django 5.1.5 on 2025-05-15 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0009_remove_listing_pictures_lg_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="search_terms",
            field=models.CharField(default="", max_length=100),
        ),
    ]
