import os
from random import random, choice

from apps.accounts.models import User
from core.settings import BASE_DIR


def run():
    first_names_male = [
        "James",
        "John",
        "Robert",
        "Michael",
        "William",
        "David",
        "Joseph",
        "Thomas",
        "Charles",
        "Christopher",
        "Daniel",
        "Matthew",
        "Anthony",
        "Mark",
        "Donald",
        "Steven",
        "Paul",
        "Andrew",
        "Joshua",
        "Kenneth",
        "Kevin",
        "Brian",
        "George",
        "Timothy",
        "Ronald",
        "Jason",
        "Edward",
        "Jeffrey",
        "Ryan",
        "Jacob",
        "Gary",
        "Nicholas",
        "Eric",
        "Jonathan",
        "Stephen",
        "Larry",
        "Justin",
        "Scott",
        "Brandon",
        "Benjamin",
        "Samuel",
        "Gregory",
        "Alexander",
        "Patrick",
        "Frank",
        "Raymond",
        "Jack",
        "Dennis",
        "Jerry",
        "Tyler",
    ]

    first_names_female = [
        "Mary",
        "Patricia",
        "Jennifer",
        "Linda",
        "Elizabeth",
        "Barbara",
        "Susan",
        "Jessica",
        "Sarah",
        "Karen",
        "Lisa",
        "Nancy",
        "Betty",
        "Margaret",
        "Sandra",
        "Ashley",
        "Kimberly",
        "Emily",
        "Donna",
        "Michelle",
        "Carol",
        "Amanda",
        "Dorothy",
        "Melissa",
        "Deborah",
        "Stephanie",
        "Rebecca",
        "Sharon",
        "Laura",
        "Cynthia",
        "Kathleen",
        "Amy",
        "Angela",
        "Shirley",
        "Anna",
        "Ruth",
        "Brenda",
        "Pamela",
        "Nicole",
        "Katherine",
        "Samantha",
        "Christine",
        "Emma",
        "Catherine",
        "Debra",
        "Virginia",
        "Rachel",
        "Carolyn",
        "Janet",
        "Maria",
    ]

    last_names = [
        "Smith",
        "Johnson",
        "Williams",
        "Brown",
        "Jones",
        "Garcia",
        "Miller",
        "Davis",
        "Rodriguez",
        "Martinez",
        "Hernandez",
        "Lopez",
        "Gonzalez",
        "Wilson",
        "Anderson",
        "Thomas",
        "Taylor",
        "Moore",
        "Jackson",
        "Martin",
        "Lee",
        "Perez",
        "Thompson",
        "White",
        "Harris",
        "Sanchez",
        "Clark",
        "Ramirez",
        "Lewis",
        "Robinson",
        "Walker",
        "Young",
        "Allen",
        "King",
        "Wright",
        "Scott",
        "Torres",
        "Nguyen",
        "Hill",
        "Flores",
        "Green",
        "Adams",
        "Nelson",
        "Baker",
        "Hall",
        "Rivera",
        "Campbell",
        "Mitchell",
        "Carter",
        "Roberts",
    ]

    # create a list of all avatars
    rel_avatar_directory = "/static/img/dummy_avatars/"
    abs_avatar_directory = str(BASE_DIR) + rel_avatar_directory
    all_avatars = os.listdir(abs_avatar_directory)

    for i in range(100):
        if random() >= 0.5:
            first_name = choice(first_names_female)
        else:
            first_name = choice(first_names_male)
        last_name = choice(last_names)
        username = first_name + "_" + last_name
        picture_file = choice(all_avatars)
        profile_picture = rel_avatar_directory + picture_file

        new_user = User(
            username=username,
            first_name=first_name,
            last_name=last_name,
            profile_picture=profile_picture,
        )
        new_user.save()
